services:

    _defaults:
        autowire: true

    App\Application:
        public: true

    3dbpp.clientFactory:
        class: App\ThreeDBP\HttpClientFactory
        arguments:
            $endpoint: '%3dbp.endpoint%'
            $username: '%3dbp.username%'
            $apiKey: '%3dbp.apiKey%'

    3dbpp.solver:
        class: App\ThreeDBP\RemotePackingSolver
        arguments:
            $httpClient: !service
                factory: ['@3dbpp.clientFactory', 'create']

# caching
#    3dbpp.solver.cachingDecorator:
#        decorates: 3dbpp.solver
#        class: App\Cache\CachingPackingSolver

    App\Model\PackingSolver: '@3dbpp.solver'

    App\Doctrine\EntityManagerFactory:
        arguments:
            $host: '%mysql.host%'
            $user: '%mysql.user%'
            $password: '%mysql.password%'
            $dbname: '%mysql.dbname%'

    Doctrine\ORM\EntityManagerInterface:
        # the first argument is the class and the second argument is the static method
        factory: ['@App\Doctrine\EntityManagerFactory', 'create']

    Psr\Log\LoggerInterface:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments:
            $output: !service
                class: Symfony\Component\Console\Output\ConsoleOutput
#
#    Symfony\Component\Validator\Validator\ValidatorInterface:
#        class:
